
sineComponents = ["sin(wt)sin(wet)";...
                  'cos(wt)sin(wet)';...
                  'sin(wt)cos(wet)';...
                  'cos(wt)cos(wet)';...
                  'sin(wt)';        ...
                  'cos(wt)';        ...
                  'sin(wot)';       ...
                  'cos(wot)';       ...
                  'sin(wet)';       ...
                  'cos(wet)';       ...
                  't (Linear)';     ...
                  '1 (Constant)'];


for count = 1:columns(ampFreq)-1
  figure(count);
  semilogx(ampFreq(:,1),ampFreq(:,count+1));
  title(sineComponents(count,:));
endfor

